name: Build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - uses: actions/setup-node@v3
              with:
                  node-version: 'lts/Iron'
                  cache: 'npm'

            - uses: mymindstorm/setup-emsdk@v11
              with:
                  version: 3.1.48
                  actions-cache-folder: 'emsdk-cache'

            - run: cmake --version
            - run: c++ -v
            - run: em++ -v

            - run: npm ci
            - run: npm run build
            - run: xvfb-run -a npm run test
            - run: npm run package

            - uses: actions/upload-artifact@v3
              with:
                  name: sksl.vsix
                  path: sksl.vsix
