name: Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - uses: actions/setup-node@v3
              with:
                  node-version: 'lts/Hydrogen'
                  cache: 'npm'

            - run: npm ci
            - run: npm run test
